FROM node:18-alpine AS base

RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock ./
RUN yarn global add pnpm && pnpm i --frozen-lockfile
COPY . .

RUN yarn build

ENV NODE_ENV="production"

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "start"]