name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -f Dockerfile.production -t nextjs-socket-io-demo .
      - name: Add the tag for the Docker image
        run: docker tag nextjs-socket-io-demo othytenk/nextjs-socket-io-demo:latest
      - name: Push to Dockerhub
        run: docker push othytenk/nextjs-socket-io-demo:latest
